import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

const CONVENTIONS = {
	pom: {
		description: "Page Object Model is mandatory. Locators and actions must live in page classes, never in spec files.",
		uiPagesPath: "src/pages/ui/",
		apiPagesPath: "src/pages/api/",
		basePage: "src/pages/ui/base-page.ts",
		importPattern: "import { TodoPage } from 'pages/ui';",
		fixturesPath: "src/tests/ui/fixtures/",
		fixtureImport: "import { test } from '../fixtures/<app>-fixture'; // NOT from @playwright/test",
		rules: [
			"Every UI interaction must go through a page object method",
			"Spec files call page methods only — no raw page.locator(), page.click(), page.fill() in tests",
			"Each page class extends BasePage",
			"Locators are defined as class properties in the constructor, not inline in test steps",
			"Actions and assertions are single-purpose methods",
			"Import test from the fixture file, never directly from @playwright/test",
		],
	},
	tagging: {
		description: "Every test must have at least one tag from the TAGS enum defined in utils/configuration.ts",
		validTags: ["@regression", "@smoke", "@customer", "@internal"],
		usage: "test('test name', { tag: [TAGS.SMOKE, TAGS.REGRESSION] }, async ({ todoPage }) => { ... })",
		importStatement: "import { TAGS } from '@utils/configuration';",
		priorityMapping: {
			High: "TAGS.SMOKE",
			Medium: "TAGS.REGRESSION",
			Low: "TAGS.REGRESSION",
		},
		rules: [
			"@smoke: critical path tests, fast execution, run on every deploy",
			"@regression: full coverage, run before releases",
			"@customer: customer-facing flows",
			"@internal: internal/admin flows",
			"AI-generated tests must be tagged before committing",
		],
	},
	locators: {
		description: "Locator preference order. Use the highest priority strategy available.",
		priority: [
			"1st: data-test attribute — page.getByTestId('submit-btn')",
			"2nd: ARIA role — page.getByRole('button', { name: 'Submit' })",
			"3rd: Label — page.getByLabel('Email address')",
			"4th: Placeholder — page.getByPlaceholder('Enter email')",
			"5th: Text — page.getByText('Submit') — only for static, unique text",
			"NEVER: CSS class selectors, XPath, or positional selectors",
		],
		rules: [
			"Never use dynamic IDs or auto-generated class names",
			"Locators must be defined as class properties in the page object, not inline in test steps",
			"If data-test attribute is missing, note it as a recommendation in a comment",
		],
	},
	testSteps: {
		description: "All logical actions must be wrapped in test.step() for report readability.",
		usage: "await test.step('Add a todo item', async () => { await todoPage.addTodo(TODO_ITEMS[0]); });",
		rules: [
			"Every logical group of actions must be wrapped in test.step()",
			"Never use inline comments as step markers — use test.step() instead",
			"Step descriptions should match the scenario step text from the plan",
		],
	},
	mockData: {
		description: "All test data must come from shared/mock-data. Never hardcode strings in test files.",
		path: "src/shared/mock-data/",
		importPattern: "import { TODO_ITEMS, LOCAL_STORAGE_ID } from 'shared/mock-data';",
		rules: [
			"Never hardcode test data strings in spec files",
			"If required data doesn't exist in shared/mock-data, add it there first",
			"Use LOCAL_STORAGE_ID constant for localStorage checks",
		],
	},
	environmentVariables: {
		description: "All URLs and credentials come from environment variables. Never hardcode.",
		variables: {
			BASE_URL: "process.env.DEMO_PLAYWRIGHT_DEV_URL — Todo app demo URL",
			API_BASE_URL: "process.env.API_BASE_URL — API base URL",
			ENVIRONMENT: "process.env.ENVIRONMENT — current environment name",
			SAUCE_DEMO_URL: "process.env.SAUCE_DEMO_URL — SauceDemo app URL",
			SAUCE_DEMO_USERNAME: "process.env.SAUCE_DEMO_USERNAME — SauceDemo login username",
			SAUCE_DEMO_PASSWORD: "process.env.SAUCE_DEMO_PASSWORD — SauceDemo login password",
		},
		rules: [
			"Never hardcode http:// or https:// URLs in test files",
			"Never hardcode credentials in test files",
			"URL is handled in the fixture — spec files never call page.goto() directly",
		],
	},
	fileStructure: {
		specFiles: "src/tests/ui/<feature-name>.spec.ts for UI tests",
		generatedSpecs: "src/tests/ui/generated/<scenario-kebab>.spec.ts for AI-generated tests",
		fixtures: "src/tests/ui/fixtures/<feature>-fixture.ts",
		mockData: "src/shared/mock-data/<feature>-data.ts",
		pages: "src/pages/ui/<feature>-page.ts",
		plans: "specs/<feature-name>-plan.md — planner output",
		naming: "kebab-case for files, PascalCase for class names",
	},
	generatedTestHeaders: {
		description: "All AI-generated tests must include these header comments.",
		required: [
			"// @generated by playwright-test-orchestrator (or playwright-test-generator)",
			"// spec: specs/<plan-file>.md",
			"// scenario: <scenario title>",
			"// req: REQ-NNN, REQ-NNN",
		],
	},
};

export function getFrameworkConventions(server: McpServer): void {
	server.registerTool(
		"get_framework_conventions",
		{
			description:
				"Get this project's QA framework conventions before writing any code. Returns POM rules, tagging strategy, locator preferences, fixture/mock-data usage, and file naming. All generated tests must comply with these conventions.",
			inputSchema: {
				section: z
					.enum(["all", "pom", "tagging", "locators", "testSteps", "mockData", "environmentVariables", "fileStructure", "generatedTestHeaders"])
					.optional()
					.describe("Which section to return. Defaults to 'all'."),
			},
		},
		async ({ section = "all" }) => {
			const data = section === "all" ? CONVENTIONS : { [section]: CONVENTIONS[section as keyof typeof CONVENTIONS] };
			return {
				content: [
					{
						type: "text" as const,
						text:
							`# Framework Conventions${section !== "all" ? ` — ${section}` : ""}\n\n` +
							`These conventions are enforced via pre-commit hooks and CI. Violations block commits.\n\n` +
							`\`\`\`json\n${JSON.stringify(data, null, 2)}\n\`\`\``,
					},
				],
			};
		},
	);
}
