import { readdirSync, readFileSync, existsSync } from "fs";
import { join } from "path";

const HEALTH_FILE = join(__dirname, "..", "test-health.json");

function readBaselineAssertionCounts(): Record<string, number> {
	if (!existsSync(HEALTH_FILE)) return {};
	try {
		const data = JSON.parse(readFileSync(HEALTH_FILE, "utf-8"));
		const out: Record<string, number> = {};
		for (const [file, record] of Object.entries(data as Record<string, { baselineAssertionCount?: number }>)) {
			if (record.baselineAssertionCount !== undefined) out[file] = record.baselineAssertionCount;
		}
		return out;
	} catch {
		return {};
	}
}

const ROOT = join(__dirname, "..");
const GENERATED_DIR = join(ROOT, "src", "tests", "ui", "generated");
const REQUIREMENTS_DIR = join(ROOT, "requirements");

interface FileResult {
	file: string;
	passed: boolean;
	violations: string[];
}

// ---------------------------------------------------------------------------
// Quality rules — each returns a violation string or null if passing
// ---------------------------------------------------------------------------

const rules: Array<{ name: string; check: (content: string) => string | null }> = [
	{
		name: "@generated header",
		check: (c) => (c.includes("// @generated by") ? null : "Missing '// @generated by' header"),
	},
	{
		name: "spec reference",
		check: (c) => (c.includes("// spec:") ? null : "Missing '// spec: <plan-file>' reference"),
	},
	{
		name: "scenario reference",
		check: (c) => (c.includes("// scenario:") ? null : "Missing '// scenario: <title>' reference"),
	},
	{
		name: "req reference",
		check: (c) =>
			c.includes("// req:") ? null : "Missing '// req: REQ-NNN' traceability comment — link this test to a requirement",
	},
	{
		name: "test.describe block",
		check: (c) => (c.includes("test.describe(") ? null : "No test.describe() block — generated tests must be grouped"),
	},
	{
		name: "no waitForTimeout",
		check: (c) =>
			c.includes("waitForTimeout") ? "Found waitForTimeout() — use Playwright auto-waiting instead" : null,
	},
	{
		name: "no networkidle",
		check: (c) => (c.includes("networkidle") ? "Found 'networkidle' — unreliable, use auto-waiting" : null),
	},
	{
		name: "no hardcoded sleep",
		check: (c) =>
			/setTimeout\s*\(|await\s+new\s+Promise.*resolve.*\d+/.test(c)
				? "Found hardcoded sleep — use Playwright auto-waiting"
				: null,
	},
	{
		name: "has expect assertions",
		check: (c) => (c.includes("expect(") ? null : "No expect() assertions found"),
	},
	{
		name: "no assertion predicate weakening",
		check: (c) => {
			// Detect patterns where a healer may have replaced a strict predicate with a looser one.
			// These are not forbidden in new tests, but should never appear as a replacement for
			// toBeHidden / toHaveCount / toHaveText etc. This rule catches the most common cheat:
			// commenting out an expect() call entirely (leaving only the locator expression).
			const commented = c.match(/\/\/\s*await\s+expect\s*\(/g);
			if (commented && commented.length > 0)
				return `Found ${commented.length} commented-out expect() call(s) — restore or remove them`;
			return null;
		},
	},
	{
		name: "no test.only",
		check: (c) => (c.includes("test.only(") ? "Found test.only() — remove before committing" : null),
	},
];

// ---------------------------------------------------------------------------
// Per-file validation
// ---------------------------------------------------------------------------

function countAssertions(content: string): number {
	return (content.match(/\bexpect\s*\(/g) ?? []).length;
}

function validateFile(filePath: string, baselineCounts: Record<string, number>): FileResult {
	const file = filePath.replace(ROOT + "/", "").replace(/\\/g, "/");
	const content = readFileSync(filePath, "utf-8");
	const violations = rules.map((r) => r.check(content)).filter((v): v is string => v !== null);

	const baseline = baselineCounts[file];
	if (baseline !== undefined) {
		const current = countAssertions(content);
		if (current < baseline) {
			violations.push(
				`Assertion count dropped from ${baseline} to ${current} — a heal may have removed or weakened assertions. ` +
				`Restore the missing expect() calls or get explicit approval to change them.`
			);
		}
	}

	return { file, passed: violations.length === 0, violations };
}

// ---------------------------------------------------------------------------
// REQ coverage check
// ---------------------------------------------------------------------------

function extractReqIds(content: string): string[] {
	const match = content.match(/\/\/ req: (.+)/);
	if (!match) return [];
	return match[1].split(",").map((s) => s.trim());
}

function loadAllRequirementIds(): string[] {
	if (!existsSync(REQUIREMENTS_DIR)) return [];
	const ids: string[] = [];
	for (const file of readdirSync(REQUIREMENTS_DIR).filter((f: string) => f.endsWith(".md"))) {
		const content = readFileSync(join(REQUIREMENTS_DIR, file), "utf-8");
		for (const m of content.matchAll(/###\s+(REQ-\d+)/g)) {
			ids.push(m[1]);
		}
	}
	return ids;
}

function checkRequirementCoverage(generatedFiles: string[]): void {
	const allReqIds = loadAllRequirementIds();
	if (allReqIds.length === 0) return;

	const coveredIds = new Set<string>();
	for (const file of generatedFiles) {
		for (const id of extractReqIds(readFileSync(file, "utf-8"))) {
			coveredIds.add(id);
		}
	}

	const uncovered = allReqIds.filter((id) => !coveredIds.has(id));

	console.log(`\nRequirements Coverage`);
	console.log(`─────────────────────────────────────────`);
	console.log(`Total requirements : ${allReqIds.length}`);
	console.log(`Covered by tests   : ${coveredIds.size}`);

	if (uncovered.length > 0) {
		console.log(`\n⚠  Uncovered requirements (no generated test references these):`);
		for (const id of uncovered) console.log(`   ${id}`);
	} else {
		console.log(`✓  All requirements have test coverage.`);
	}
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
	if (!existsSync(GENERATED_DIR)) {
		console.log("No generated tests directory found — nothing to validate.");
		process.exit(0);
	}

	const files = readdirSync(GENERATED_DIR)
		.filter((f: string) => f.endsWith(".spec.ts"))
		.map((f: string) => join(GENERATED_DIR, f));

	if (files.length === 0) {
		console.log("No generated test files found — nothing to validate.");
		process.exit(0);
	}

	console.log(`\nValidating ${files.length} generated test file(s)...\n`);

	const baselineCounts = readBaselineAssertionCounts();
	const results = files.map((f) => validateFile(f, baselineCounts));
	const passed = results.filter((r) => r.passed);
	const failed = results.filter((r) => !r.passed);

	for (const result of results) {
		console.log(`${result.passed ? "✓" : "✗"} ${result.file}`);
		for (const v of result.violations) console.log(`    ${v}`);
	}

	console.log(`\n─────────────────────────────────────────`);
	console.log(`Quality gate: ${passed.length} / ${results.length} passed`);

	checkRequirementCoverage(files);

	if (failed.length > 0) {
		console.log(`\nFix violations above before merging generated tests.\n`);
		process.exit(1);
	}

	console.log(`\nAll checks passed.\n`);
	process.exit(0);
}

main();
